### ISSUE TITLE
backing up wont work HELP

### ISSUE THREAD

**Issue by df12435678** [zoogie/Kartminer7#15]
Ive tried following 3ds hacks guide. it says i need to go to backups and run the correct region but if I try any of them my command prompt says that “../resources/save3ds_fuse.exe” is not recognized as an internal or external command, operable program or batch file” what do I do?
![image](https://github.com/zoogie/Kartminer7/assets/140760060/b991ddfb-ba3c-45a9-b3b1-6dd7aa396f4d)

**Comment by df12435678** [comment]
actually instead of the backup, it just wont excecute the release

**Comment by zoogie** [comment]
This will happen if you run the .bat as an Administrator. You need to run as a user.

**Comment by SQSAPelugo15** [comment]
![image](https://github.com/zoogie/Kartminer7/assets/141353189/fbd2710e-fc77-4f40-b079-6edb1fad153e)
Im following 3ds hack guide it says i need to go to backups and run the correct region but when i clicked on my 3ds region i have this problem, can any help my?

**Comment by zoogie** [comment]
The movable.sed from your console needs to be in the /resources folder for this to work.
Seedminer is the process to obtain that file. 
https://3ds.hacks.guide/seedminer-(alternate).html

**Comment by austinthedeveloper** [comment]
I'm having the same issue. The `movable.sed` file is in `resources`. I've run The `backup_USA` in my cmd using both Administrator and User. 

![image](https://github.com/zoogie/Kartminer7/assets/2235324/7106466f-5147-4434-ac0e-5d2709b2f57b)

**Comment by zoogie** [comment]
> I'm having the same issue. The `movable.sed` file is in `resources`. I've run The `backup_USA` in my cmd using both Administrator and User.
> 
> ![image](https://user-images.githubusercontent.com/2235324/258621119-7106466f-5147-4434-ac0e-5d2709b2f57b.png)

Try to just double click the USA.bat script. It needs to open in the directory it exists in.
If that's not the issue, and you're getting something like [SQSAPelugo15](https://github.com/SQSAPelugo15)'s images, you might have the incorrect movable.sed.
