### ISSUE TITLE
(URGENT HELP) After opening the backup or any other batch file the control terminal says  "The system cannot find the path specified."

### ISSUE THREAD

**Issue by Ultrafunzzz** [zoogie/Kartminer7#27]
Every time a batch file is opening this prompt appears: _ERROR - Host IO error: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." } IO error from host file system: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." } Error: IO(Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." })_ .bat files seem to be the issue. I've tried all the other ones and the same prompt appears which means I can't finish the Kartminer7 process. Andy4169 is also having the same problem so it would be nice if you could find a solution for this so I can finish because I am now stuck halfway through the tutorial. Thanks, Ultrafunzzz

**Comment by Ultrafunzzz** [comment]
Another thing I found out now is that when run with an administrator there is no red text but it still does not   complete and close the prompt and make a file.

**Comment by zoogie** [comment]
One issue enough.
