### ISSUE TITLE
Problem at last step

### ISSUE THREAD

**Issue by mzahoran** [zoogie/Kartminer7#6]
When I enter street pass list it freezes and sends a 3ds message saying there was an error and its forcing a restart. Do you know where I may have went wrong and if I should start over which step should I start from, would I need a new movable.sed? just let me know what you think.

**Comment by mzahoran** [comment]
![image](https://github.com/zoogie/Kartminer7/assets/131494205/b02e938b-2da1-44f8-a00f-2c5482b96bad)

**Comment by mzahoran** [comment]
That's the screen I reach then it forces a restart.

**Comment by zoogie** [comment]
I need to know your 3ds region.

**Comment by mzahoran** [comment]
old usa

**Comment by zoogie** [comment]
Ok, move to issue #3 and try the test on the 2nd to last post "USA_test3_mk7v1.2.zip"

Closing this issue b/c duplicate issue.
